### ISSUE TITLE
Not sure what I'm doing wrong as this plugin is not working for me

### ISSUE THREAD

**Issue by DataSciLearner** [SimonTC/obsidian-note-autocreation#8]
Hi,
This plugin doesn't seem to be working for me. It brings up the context menu with folders but doesn't create any new file when I add any new words. It doesn't create a new file when I simply type `@new note` either.
I did restart Obsidian after installing the plugin.
Can you kindly help resolve this?
Regards.

**Comment by SimonTC** [comment]
I will see what I can do.
Can you give me the following information:

- Obsidian version
- Plugin version
- What device are you running Obsidian on

I would also like you to enable the Obsidian console and copy any messages shown when you try to add a new file.
You enable the console by using the hotkey `cmd+ option + i ` on Mac or `ctrl + shift + i` on Windows. If you are using a mobile device or tablet, I'm not sure how to show the console so in that case I can live without the console information.

**Comment by aeluabik** [comment]
I know it is been quite long, but I'm having a similar issue. Here's what I got:
Obsidian version: v1.1.14
Plugin version. v1.3.3
Running on MacOS

```
app.js:1 
Uncaught TypeError: Cannot read properties of null (reading 'frontmatter')
    at isFmDisable (plugin:auto-note-mover:1806:68)
    at fileCheck (plugin:auto-note-mover:2079:13)
    at eval (plugin:auto-note-mover:2125:66)
    at t.e.tryTrigger (app.js:1:1060977)
    at t.e.trigger (app.js:1:1060910)
    at t.trigger (app.js:1:1129068)
    at t.onChange (app.js:1:1119431)
    at e.trigger (app.js:1:1108826)
    at e.<anonymous> (app.js:1:1106898)
    at app.js:1:235836
```

﻿

**Comment by SimonTC** [comment]
@aeluabik from the log lines it looks like the issue is related to the auto-note-mover plugin. Could you try to disable that plugin and see if notes then are created? If it is possible to create notes with that plugin disabled I can try to investigate why the two plugins don't work together.

**Comment by aeluabik** [comment]
@SimonTC I did it and it still didn't work. Let me describer the problem better: when I type the character to create a list, it allows me to create one when I type one word; when adding more words, it stops working. 
If it is not too annoying, I'd like to ask you to add an option for link auto creation when using normal [[]] md link creation. Also, if it could check for the links without notes inside the vault, would be great, because I reference multiple stuff out of obsidian (using readwise for example) and I wish they would be auto-created

**Comment by SimonTC** [comment]
> If it is not too annoying, I'd like to ask you to add an option for link auto creation when using normal [[]] md link creation

It is unfortunately not possible to override the functionality of link insertion using [[]] md link creation. I originally tried to hook into that functionality, but there is no API for me to do it. That is why Note Auto Creator has to use a separate character. You could change the trigger for link insertion to `[`, but since `[` is a reserved symbol in markdown I think it would bring more trouble than it is worth.

>  if it could check for the links without notes inside the vault, would be great
If I understand correctly, then the plugin actually already  can suggest links without notes and create the notes if you reference that link. This functionality is controlled by the setting `Suggest existing links to notes that do not exist`.  

> UPDATE: it was an issue with Various complements plugin
I just tried enabling the Various complements plugin and I couldn't see the issue you are describing. I was using default settings, so that might be why. I think you should be able to add the Note Auto Creation trigger (default @) to the list of `First characters to disable suggestions` in Various complements to maybe help the issue you were seeing. That way there is a bigger chance that Various complements won't take control.

**Comment by SimonTC** [comment]
Closing since there has been no updates for a long time
